name: Endocrine Monthly Bot

on:
  schedule:
    # Her ayın 1. günü saat 09:00 UTC (Türkiye için 12:00)
    - cron: "0 9 1 * *"
  workflow_dispatch:   # Manuel tetikleme (Actions sekmesinden Run Workflow)
  push:                # Commit sonrası test amaçlı tetikleme
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          UNPAYWALL_EMAIL: ${{ secrets.UNPAYWALL_EMAIL }}
          LOOKBACK_DAYS: 30
          MAX_RESULTS_PER_JOURNAL: 250
        run: |
          python main.py
